# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from pprl_data_owner_service_api_client.models.data_set_modifier_config import DataSetModifierConfig
from pprl_data_owner_service_api_client.models.selector_record import SelectorRecord
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DataSetGeneratorConfig(BaseModel):
    """
    Configuration for generating the corrupted dataset
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Name of the configuration")
    original_size: Optional[StrictInt] = Field(default=None, description="Number of records from the original source", alias="originalSize")
    modified_size: Optional[StrictInt] = Field(default=None, description="Number of records from the modified source", alias="modifiedSize")
    source_overlap: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Share of records from original source that have a duplicate in modified source", alias="sourceOverlap")
    input_filter: Optional[SelectorRecord] = Field(default=None, description="Filter the input records before using them in the generator", alias="inputFilter")
    source_modifier_configs: Optional[List[DataSetModifierConfig]] = Field(default=None, description="Modifiers to sequentially apply on the input records before creating the modified two-source dataset", alias="sourceModifierConfigs")
    duplicate_modifier_configs: Optional[List[DataSetModifierConfig]] = Field(default=None, description="Modifiers to create true matches and true non-matches", alias="duplicateModifierConfigs")
    seed: Optional[StrictInt] = Field(default=None, description="Global seed for randomness, e.g., when shuffling the input records before corruption  Take care: Does not necessarily affect random selectors within modifier configs!")
    modifier_distribution_strategy: Optional[StrictStr] = Field(default=None, description="Setting on how to apply the duplicateModifierConfigs", alias="modifierDistributionStrategy")
    var_class: StrictStr = Field(alias="@class")
    __properties: ClassVar[List[str]] = ["name", "originalSize", "modifiedSize", "sourceOverlap", "inputFilter", "sourceModifierConfigs", "duplicateModifierConfigs", "seed", "modifierDistributionStrategy", "@class"]

    @field_validator('modifier_distribution_strategy')
    def modifier_distribution_strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['UNISIZE', 'UNISIZE_RELAXED']):
            raise ValueError("must be one of enum values ('UNISIZE', 'UNISIZE_RELAXED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataSetGeneratorConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input_filter
        if self.input_filter:
            _dict['inputFilter'] = self.input_filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in source_modifier_configs (list)
        _items = []
        if self.source_modifier_configs:
            for _item_source_modifier_configs in self.source_modifier_configs:
                if _item_source_modifier_configs:
                    _items.append(_item_source_modifier_configs.to_dict())
            _dict['sourceModifierConfigs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in duplicate_modifier_configs (list)
        _items = []
        if self.duplicate_modifier_configs:
            for _item_duplicate_modifier_configs in self.duplicate_modifier_configs:
                if _item_duplicate_modifier_configs:
                    _items.append(_item_duplicate_modifier_configs.to_dict())
            _dict['duplicateModifierConfigs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataSetGeneratorConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "originalSize": obj.get("originalSize"),
            "modifiedSize": obj.get("modifiedSize"),
            "sourceOverlap": obj.get("sourceOverlap"),
            "inputFilter": SelectorRecord.from_dict(obj["inputFilter"]) if obj.get("inputFilter") is not None else None,
            "sourceModifierConfigs": [DataSetModifierConfig.from_dict(_item) for _item in obj["sourceModifierConfigs"]] if obj.get("sourceModifierConfigs") is not None else None,
            "duplicateModifierConfigs": [DataSetModifierConfig.from_dict(_item) for _item in obj["duplicateModifierConfigs"]] if obj.get("duplicateModifierConfigs") is not None else None,
            "seed": obj.get("seed"),
            "modifierDistributionStrategy": obj.get("modifierDistributionStrategy"),
            "@class": obj.get("@class")
        })
        return _obj


