# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from pprl_data_owner_service_api_client.models.encoding_id_dto import EncodingIdDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EncodingCreationRequestDto(BaseModel):
    """
    Request for creating an encoding definition.
    """ # noqa: E501
    weight_selection_method: Optional[StrictStr] = Field(default=None, alias="weightSelectionMethod")
    frequency_selection_method: Optional[StrictStr] = Field(default=None, alias="frequencySelectionMethod")
    encoding_creation_method: Optional[StrictStr] = Field(default=None, alias="encodingCreationMethod")
    base_encoding_id: Optional[EncodingIdDto] = Field(default=None, alias="baseEncodingId")
    output_encoding_id: Optional[EncodingIdDto] = Field(default=None, alias="outputEncodingId")
    attribute_weights: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, alias="attributeWeights")
    attribute_length: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, alias="attributeLength")
    source_specific: Optional[StrictBool] = Field(default=None, alias="sourceSpecific")
    attribute_error_rates: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, description="Precomputed/estimated error rates.Required if sourceSpecific = true because the error rate cannot be determined per source.", alias="attributeErrorRates")
    source_specific_attribute_weights: Optional[Dict[str, Dict[str, Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Attribute weights for each data source. Only relevant if sourceSpecific = true.", alias="sourceSpecificAttributeWeights")
    source_specific_attribute_length: Optional[Dict[str, Dict[str, Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Attribute lengths for each data source. Only relevant if sourceSpecific = true.", alias="sourceSpecificAttributeLength")
    sources: Optional[List[StrictStr]] = Field(default=None, description="Names of sources. Only relevant for sourceSpecific = true and WeightSelectionMethod.None.")
    dataset_id: Optional[StrictInt] = Field(default=None, alias="datasetId")
    average_fillrate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="averageFillrate")
    max_fillrate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maxFillrate")
    bloom_filter_size: Optional[StrictInt] = Field(default=None, alias="bloomFilterSize")
    persist: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["weightSelectionMethod", "frequencySelectionMethod", "encodingCreationMethod", "baseEncodingId", "outputEncodingId", "attributeWeights", "attributeLength", "sourceSpecific", "attributeErrorRates", "sourceSpecificAttributeWeights", "sourceSpecificAttributeLength", "sources", "datasetId", "averageFillrate", "maxFillrate", "bloomFilterSize", "persist"]

    @field_validator('weight_selection_method')
    def weight_selection_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'FELLEGI_SUNTER']):
            raise ValueError("must be one of enum values ('NONE', 'FELLEGI_SUNTER')")
        return value

    @field_validator('frequency_selection_method')
    def frequency_selection_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'DATABASE']):
            raise ValueError("must be one of enum values ('NONE', 'DATABASE')")
        return value

    @field_validator('encoding_creation_method')
    def encoding_creation_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BASE_ENCODING_ADAPTION', 'RBF', 'ABF']):
            raise ValueError("must be one of enum values ('BASE_ENCODING_ADAPTION', 'RBF', 'ABF')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EncodingCreationRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base_encoding_id
        if self.base_encoding_id:
            _dict['baseEncodingId'] = self.base_encoding_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output_encoding_id
        if self.output_encoding_id:
            _dict['outputEncodingId'] = self.output_encoding_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EncodingCreationRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "weightSelectionMethod": obj.get("weightSelectionMethod"),
            "frequencySelectionMethod": obj.get("frequencySelectionMethod"),
            "encodingCreationMethod": obj.get("encodingCreationMethod"),
            "baseEncodingId": EncodingIdDto.from_dict(obj["baseEncodingId"]) if obj.get("baseEncodingId") is not None else None,
            "outputEncodingId": EncodingIdDto.from_dict(obj["outputEncodingId"]) if obj.get("outputEncodingId") is not None else None,
            "attributeWeights": obj.get("attributeWeights"),
            "attributeLength": obj.get("attributeLength"),
            "sourceSpecific": obj.get("sourceSpecific"),
            "attributeErrorRates": obj.get("attributeErrorRates"),
            "sourceSpecificAttributeWeights": obj.get("sourceSpecificAttributeWeights"),
            "sourceSpecificAttributeLength": obj.get("sourceSpecificAttributeLength"),
            "sources": obj.get("sources"),
            "datasetId": obj.get("datasetId"),
            "averageFillrate": obj.get("averageFillrate"),
            "maxFillrate": obj.get("maxFillrate"),
            "bloomFilterSize": obj.get("bloomFilterSize"),
            "persist": obj.get("persist")
        })
        return _obj


