# coding: utf-8

# flake8: noqa
"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from pprl_data_generator_service_api_client.models.attribute_dto import AttributeDto
from pprl_data_generator_service_api_client.models.change_filter import ChangeFilter
from pprl_data_generator_service_api_client.models.cluster_order_request import ClusterOrderRequest
from pprl_data_generator_service_api_client.models.content_filter import ContentFilter
from pprl_data_generator_service_api_client.models.date_info import DateInfo
from pprl_data_generator_service_api_client.models.duplicate import Duplicate
from pprl_data_generator_service_api_client.models.encoding_id_dto import EncodingIdDto
from pprl_data_generator_service_api_client.models.generic_raw_record import GenericRawRecord
from pprl_data_generator_service_api_client.models.generic_raw_record_with_dates import GenericRawRecordWithDates
from pprl_data_generator_service_api_client.models.germany_generator_config import GermanyGeneratorConfig
from pprl_data_generator_service_api_client.models.link import Link
from pprl_data_generator_service_api_client.models.ncvr_panse_import_request import NcvrPanseImportRequest
from pprl_data_generator_service_api_client.models.object_id import ObjectId
from pprl_data_generator_service_api_client.models.record_cluster import RecordCluster
from pprl_data_generator_service_api_client.models.record_dto import RecordDto
from pprl_data_generator_service_api_client.models.record_id_dto import RecordIdDto
from pprl_data_generator_service_api_client.models.tag import Tag
from pprl_data_generator_service_api_client.models.tagged_dataset_dto import TaggedDatasetDto
from pprl_data_generator_service_api_client.models.time_filter import TimeFilter
from pprl_data_generator_service_api_client.models.usvr_selection_config import UsvrSelectionConfig

