# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from pprl_data_generator_service_api_client.models.change_filter import ChangeFilter
from pprl_data_generator_service_api_client.models.content_filter import ContentFilter
from pprl_data_generator_service_api_client.models.time_filter import TimeFilter
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UsvrSelectionConfig(BaseModel):
    """
    UsvrSelectionConfig
    """ # noqa: E501
    dataset_variant_suffix: Optional[StrictStr] = Field(default=None, alias="datasetVariantSuffix")
    cluster_type: Optional[StrictStr] = Field(default=None, alias="clusterType")
    num_records_a: Optional[StrictInt] = Field(default=None, alias="numRecordsA")
    num_records_b: Optional[StrictInt] = Field(default=None, alias="numRecordsB")
    num_duplicates: Optional[StrictInt] = Field(default=None, alias="numDuplicates")
    num_clusters: Optional[StrictInt] = Field(default=None, alias="numClusters")
    snapshot_date_a: Optional[StrictStr] = Field(default=None, alias="snapshotDateA")
    snapshot_date_b: Optional[StrictStr] = Field(default=None, alias="snapshotDateB")
    source_a: Optional[StrictStr] = Field(default=None, alias="sourceA")
    source_b: Optional[StrictStr] = Field(default=None, alias="sourceB")
    attribute_columns: Optional[List[StrictStr]] = Field(default=None, alias="attributeColumns")
    ordering_strategy: Optional[StrictStr] = Field(default=None, alias="orderingStrategy")
    ordering_seed: Optional[StrictStr] = Field(default=None, alias="orderingSeed")
    fix_yob_jitter: Optional[StrictBool] = Field(default=None, alias="fixYobJitter")
    change_filter: Optional[ChangeFilter] = Field(default=None, alias="changeFilter")
    time_filter: Optional[TimeFilter] = Field(default=None, alias="timeFilter")
    content_filter: Optional[ContentFilter] = Field(default=None, alias="contentFilter")
    __properties: ClassVar[List[str]] = ["datasetVariantSuffix", "clusterType", "numRecordsA", "numRecordsB", "numDuplicates", "numClusters", "snapshotDateA", "snapshotDateB", "sourceA", "sourceB", "attributeColumns", "orderingStrategy", "orderingSeed", "fixYobJitter", "changeFilter", "timeFilter", "contentFilter"]

    @field_validator('cluster_type')
    def cluster_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['nc']):
            raise ValueError("must be one of enum values ('nc')")
        return value

    @field_validator('ordering_strategy')
    def ordering_strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SEEDED_SHUFFLE', 'DB_ORDER']):
            raise ValueError("must be one of enum values ('SEEDED_SHUFFLE', 'DB_ORDER')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsvrSelectionConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of change_filter
        if self.change_filter:
            _dict['changeFilter'] = self.change_filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of time_filter
        if self.time_filter:
            _dict['timeFilter'] = self.time_filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of content_filter
        if self.content_filter:
            _dict['contentFilter'] = self.content_filter.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsvrSelectionConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datasetVariantSuffix": obj.get("datasetVariantSuffix"),
            "clusterType": obj.get("clusterType"),
            "numRecordsA": obj.get("numRecordsA"),
            "numRecordsB": obj.get("numRecordsB"),
            "numDuplicates": obj.get("numDuplicates"),
            "numClusters": obj.get("numClusters"),
            "snapshotDateA": obj.get("snapshotDateA"),
            "snapshotDateB": obj.get("snapshotDateB"),
            "sourceA": obj.get("sourceA"),
            "sourceB": obj.get("sourceB"),
            "attributeColumns": obj.get("attributeColumns"),
            "orderingStrategy": obj.get("orderingStrategy"),
            "orderingSeed": obj.get("orderingSeed"),
            "fixYobJitter": obj.get("fixYobJitter"),
            "changeFilter": ChangeFilter.from_dict(obj["changeFilter"]) if obj.get("changeFilter") is not None else None,
            "timeFilter": TimeFilter.from_dict(obj["timeFilter"]) if obj.get("timeFilter") is not None else None,
            "contentFilter": ContentFilter.from_dict(obj["contentFilter"]) if obj.get("contentFilter") is not None else None
        })
        return _obj


