# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_owner_service_api_client.api.encoder_api import EncoderApi


class TestEncoderApi(unittest.TestCase):
    """EncoderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EncoderApi()

    def tearDown(self) -> None:
        pass

    def test_encode(self) -> None:
        """Test case for encode

        Encode a persisted record
        """
        pass

    def test_encode_multiple(self) -> None:
        """Test case for encode_multiple

        Bundled encoding requests for multiple persisted records
        """
        pass

    def test_encode_multiple_same(self) -> None:
        """Test case for encode_multiple_same

        Encode multiple persisted records with the same encoding
        """
        pass


if __name__ == '__main__':
    unittest.main()
