# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_owner_service_api_client.api.on_the_fly_encoder_api import OnTheFlyEncoderApi


class TestOnTheFlyEncoderApi(unittest.TestCase):
    """OnTheFlyEncoderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OnTheFlyEncoderApi()

    def tearDown(self) -> None:
        pass

    def test_encode1(self) -> None:
        """Test case for encode1

        Encode a single record
        """
        pass

    def test_encode_multiple_same1(self) -> None:
        """Test case for encode_multiple_same1

        Encode multiple records with the same encoding
        """
        pass


if __name__ == '__main__':
    unittest.main()
