# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_owner_service_api_client.api.corrupter_api import CorrupterApi


class TestCorrupterApi(unittest.TestCase):
    """CorrupterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorrupterApi()

    def tearDown(self) -> None:
        pass

    def test_corrupt_dataset(self) -> None:
        """Test case for corrupt_dataset

        Corrupt dataset
        """
        pass

    def test_get_dataset_generation_config(self) -> None:
        """Test case for get_dataset_generation_config

        Create dataset generation config
        """
        pass

    def test_get_dataset_generation_methods(self) -> None:
        """Test case for get_dataset_generation_methods

        Get dataset generation config methods
        """
        pass


if __name__ == '__main__':
    unittest.main()
