# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_owner_service_api_client.api.project_secret_management_api import ProjectSecretManagementApi


class TestProjectSecretManagementApi(unittest.TestCase):
    """ProjectSecretManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectSecretManagementApi()

    def tearDown(self) -> None:
        pass

    def test_add(self) -> None:
        """Test case for add

        Add a secret for a project
        """
        pass

    def test_get_projects(self) -> None:
        """Test case for get_projects

        Get a list of all projects that are registered with a secret
        """
        pass

    def test_remove(self) -> None:
        """Test case for remove

        Remove a secret of a project
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Override a secret of a project
        """
        pass


if __name__ == '__main__':
    unittest.main()
