# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_owner_service_api_client.models.data_set_generator_config import DataSetGeneratorConfig

class TestDataSetGeneratorConfig(unittest.TestCase):
    """DataSetGeneratorConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataSetGeneratorConfig:
        """Test DataSetGeneratorConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataSetGeneratorConfig`
        """
        model = DataSetGeneratorConfig()
        if include_optional:
            return DataSetGeneratorConfig(
                name = '',
                original_size = 56,
                modified_size = 56,
                source_overlap = 1.337,
                input_filter = pprl_data_owner_service_api_client.models.selector_record.SelectorRecord(
                    @class = '', ),
                source_modifier_configs = [
                    pprl_data_owner_service_api_client.models.data_set_modifier_config.DataSetModifierConfig(
                        tag = '', 
                        original_source_name = '', 
                        modified_source_name = '', 
                        filter_records_to_modify = pprl_data_owner_service_api_client.models.selector_record.SelectorRecord(
                            @class = '', ), 
                        record_modifiers = [
                            pprl_data_owner_service_api_client.models.selective_record_modifier.SelectiveRecordModifier(
                                modifier = pprl_data_owner_service_api_client.models.selector_record.SelectorRecord(
                                    @class = '', ), 
                                selector = , 
                                @class = '', )
                            ], 
                        attribute_modifiers = {
                            'key' : [
                                pprl_data_owner_service_api_client.models.selective_attribute_modifier.SelectiveAttributeModifier(
                                    @class = '', )
                                ]
                            }, 
                        true_duplicate = True, 
                        @class = '', )
                    ],
                duplicate_modifier_configs = [
                    pprl_data_owner_service_api_client.models.data_set_modifier_config.DataSetModifierConfig(
                        tag = '', 
                        original_source_name = '', 
                        modified_source_name = '', 
                        filter_records_to_modify = pprl_data_owner_service_api_client.models.selector_record.SelectorRecord(
                            @class = '', ), 
                        record_modifiers = [
                            pprl_data_owner_service_api_client.models.selective_record_modifier.SelectiveRecordModifier(
                                modifier = pprl_data_owner_service_api_client.models.selector_record.SelectorRecord(
                                    @class = '', ), 
                                selector = , 
                                @class = '', )
                            ], 
                        attribute_modifiers = {
                            'key' : [
                                pprl_data_owner_service_api_client.models.selective_attribute_modifier.SelectiveAttributeModifier(
                                    @class = '', )
                                ]
                            }, 
                        true_duplicate = True, 
                        @class = '', )
                    ],
                seed = 56,
                modifier_distribution_strategy = 'UNISIZE',
                var_class = ''
            )
        else:
            return DataSetGeneratorConfig(
                var_class = '',
        )
        """

    def testDataSetGeneratorConfig(self):
        """Test DataSetGeneratorConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
