# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_owner_service_api_client.api.example_controller_api import ExampleControllerApi


class TestExampleControllerApi(unittest.TestCase):
    """ExampleControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExampleControllerApi()

    def tearDown(self) -> None:
        pass

    def test_example(self) -> None:
        """Test case for example

        """
        pass


if __name__ == '__main__':
    unittest.main()
