# coding: utf-8

"""
    PPRL Data Owner Service API

    Services for the data owners for privacy-preserving record linkage, including analysing and encoding of the local dataset

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_owner_service_api_client.models.encoding_creation_response_dto import EncodingCreationResponseDto

class TestEncodingCreationResponseDto(unittest.TestCase):
    """EncodingCreationResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EncodingCreationResponseDto:
        """Test EncodingCreationResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncodingCreationResponseDto`
        """
        model = EncodingCreationResponseDto()
        if include_optional:
            return EncodingCreationResponseDto(
                request = pprl_data_owner_service_api_client.models.encoding_creation_request_dto.EncodingCreationRequestDto(
                    weight_selection_method = 'NONE', 
                    frequency_selection_method = 'NONE', 
                    encoding_creation_method = 'BASE_ENCODING_ADAPTION', 
                    base_encoding_id = pprl_data_owner_service_api_client.models.encoding_id_dto.EncodingIdDto(
                        method = '', 
                        project = '', ), 
                    output_encoding_id = pprl_data_owner_service_api_client.models.encoding_id_dto.EncodingIdDto(
                        method = '', 
                        project = '', ), 
                    attribute_weights = {
                        'key' : 1.337
                        }, 
                    attribute_length = {
                        'key' : 1.337
                        }, 
                    source_specific = True, 
                    attribute_error_rates = {
                        'key' : 1.337
                        }, 
                    source_specific_attribute_weights = {
                        'key' : {
                            'key' : 1.337
                            }
                        }, 
                    source_specific_attribute_length = {
                        'key' : {
                            'key' : 1.337
                            }
                        }, 
                    sources = [
                        ''
                        ], 
                    dataset_id = 56, 
                    average_fillrate = 1.337, 
                    max_fillrate = 1.337, 
                    bloom_filter_size = 56, 
                    persist = True, ),
                encoding = pprl_data_owner_service_api_client.models.encoding_dto.EncodingDto(
                    id = null, 
                    validation = null, 
                    config = '', )
            )
        else:
            return EncodingCreationResponseDto(
        )
        """

    def testEncodingCreationResponseDto(self):
        """Test EncodingCreationResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
