# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_linkage_unit_service_api_client.api.project_based_batch_matching_api import ProjectBasedBatchMatchingApi


class TestProjectBasedBatchMatchingApi(unittest.TestCase):
    """ProjectBasedBatchMatchingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectBasedBatchMatchingApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create new linkage project
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete a project
        """
        pass

    def test_delete_all1(self) -> None:
        """Test case for delete_all1

        Delete all projects
        """
        pass

    def test_find_all(self) -> None:
        """Test case for find_all

        Get existing linkage projects
        """
        pass

    def test_get(self) -> None:
        """Test case for get

        Get an existing linkage project
        """
        pass

    def test_reset(self) -> None:
        """Test case for reset

        Reset a linkage project
        """
        pass

    def test_run_for_new(self) -> None:
        """Test case for run_for_new

        Run a linkage project for new records
        """
        pass

    def test_run_next(self) -> None:
        """Test case for run_next

        Run (the next phase of) a linkage project
        """
        pass

    def test_run_parts(self) -> None:
        """Test case for run_parts

        Execute (parts of) a linkage project
        """
        pass


if __name__ == '__main__':
    unittest.main()
