# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_linkage_unit_service_api_client.models.matching_creation_request_dto import MatchingCreationRequestDto

class TestMatchingCreationRequestDto(unittest.TestCase):
    """MatchingCreationRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchingCreationRequestDto:
        """Test MatchingCreationRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchingCreationRequestDto`
        """
        model = MatchingCreationRequestDto()
        if include_optional:
            return MatchingCreationRequestDto(
                weight_selection_method = 'NONE',
                matching_creation_method = 'BASE_CONFIG_ADAPTION',
                base_matcher_id = pprl_linkage_unit_service_api_client.models.matcher_id_dto.MatcherIdDto(
                    method = '', 
                    project = '', ),
                output_matcher_id = pprl_linkage_unit_service_api_client.models.matcher_id_dto.MatcherIdDto(
                    method = '', 
                    project = '', ),
                attribute_weights = {
                    'key' : 1.337
                    },
                attribute_m_weights = {
                    'key' : 1.337
                    },
                attribute_u_weights = {
                    'key' : 1.337
                    },
                dataset_id = 56,
                persist = True
            )
        else:
            return MatchingCreationRequestDto(
        )
        """

    def testMatchingCreationRequestDto(self):
        """Test MatchingCreationRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
