# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_linkage_unit_service_api_client.api.transient_batch_matching_api import TransientBatchMatchingApi


class TestTransientBatchMatchingApi(unittest.TestCase):
    """TransientBatchMatchingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransientBatchMatchingApi()

    def tearDown(self) -> None:
        pass

    def test_cluster(self) -> None:
        """Test case for cluster

        Cluster and assign global IDs based on precomputed links
        """
        pass

    def test_match(self) -> None:
        """Test case for match

        Batch matcher
        """
        pass


if __name__ == '__main__':
    unittest.main()
