# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_linkage_unit_service_api_client.api.configuration_management_api import ConfigurationManagementApi


class TestConfigurationManagementApi(unittest.TestCase):
    """ConfigurationManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigurationManagementApi()

    def tearDown(self) -> None:
        pass

    def test_add(self) -> None:
        """Test case for add

        Add a configuration
        """
        pass

    def test_get_classifier_description(self) -> None:
        """Test case for get_classifier_description

        Get classifier description
        """
        pass

    def test_get_configs(self) -> None:
        """Test case for get_configs

        Get a list of all configuration IDs
        """
        pass

    def test_get_matching(self) -> None:
        """Test case for get_matching

        Get the configuration by its ID
        """
        pass

    def test_get_method_requirements(self) -> None:
        """Test case for get_method_requirements

        Get descriptions of the requirements of all matching methods
        """
        pass

    def test_remove(self) -> None:
        """Test case for remove

        Remove unused configurations
        """
        pass

    def test_remove1(self) -> None:
        """Test case for remove1

        Remove a configuration
        """
        pass

    def test_update1(self) -> None:
        """Test case for update1

        Override an existing configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
