# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_linkage_unit_service_api_client.models.matcher_trainings_request import MatcherTrainingsRequest

class TestMatcherTrainingsRequest(unittest.TestCase):
    """MatcherTrainingsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatcherTrainingsRequest:
        """Test MatcherTrainingsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatcherTrainingsRequest`
        """
        model = MatcherTrainingsRequest()
        if include_optional:
            return MatcherTrainingsRequest(
                matcher_id = pprl_linkage_unit_service_api_client.models.matcher_id_dto.MatcherIdDto(
                    method = '', 
                    project = '', ),
                dataset_id = 56,
                min_similarity = 1.337,
                max_similarity = 1.337
            )
        else:
            return MatcherTrainingsRequest(
        )
        """

    def testMatcherTrainingsRequest(self):
        """Test MatcherTrainingsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
