# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_linkage_unit_service_api_client.models.ground_truth_dto import GroundTruthDto

class TestGroundTruthDto(unittest.TestCase):
    """GroundTruthDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroundTruthDto:
        """Test GroundTruthDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroundTruthDto`
        """
        model = GroundTruthDto()
        if include_optional:
            return GroundTruthDto(
                dataset_id = 56,
                record_id_pairs = [
                    pprl_linkage_unit_service_api_client.models.record_id_pair_dto.RecordIdPairDto(
                        left_record_id = pprl_linkage_unit_service_api_client.models.record_id_dto.RecordIdDto(
                            unique = '', 
                            source = '', 
                            local = '', 
                            global = '', 
                            blocks = [
                                ''
                                ], ), 
                        right_record_id = pprl_linkage_unit_service_api_client.models.record_id_dto.RecordIdDto(
                            unique = '', 
                            source = '', 
                            local = '', 
                            global = '', ), 
                        label = 'TRUE_MATCH', )
                    ]
            )
        else:
            return GroundTruthDto(
        )
        """

    def testGroundTruthDto(self):
        """Test GroundTruthDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
