# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_linkage_unit_service_api_client.api.incremental_matcher_controller_api import IncrementalMatcherControllerApi


class TestIncrementalMatcherControllerApi(unittest.TestCase):
    """IncrementalMatcherControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IncrementalMatcherControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create1(self) -> None:
        """Test case for create1

        """
        pass

    def test_search(self) -> None:
        """Test case for search

        """
        pass


if __name__ == '__main__':
    unittest.main()
