# coding: utf-8

"""
    PPRL Protocol Manager Service API

    Protocol manager service for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_protocol_manager_service_api_client.api.service_connections_api import ServiceConnectionsApi


class TestServiceConnectionsApi(unittest.TestCase):
    """ServiceConnectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceConnectionsApi()

    def tearDown(self) -> None:
        pass

    def test_test_connections(self) -> None:
        """Test case for test_connections

        Test connections
        """
        pass


if __name__ == '__main__':
    unittest.main()
