# coding: utf-8

"""
    PPRL Protocol Manager Service API

    Protocol manager service for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_protocol_manager_service_api_client.api.protocol_analyzer_api import ProtocolAnalyzerApi


class TestProtocolAnalyzerApi(unittest.TestCase):
    """ProtocolAnalyzerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProtocolAnalyzerApi()

    def tearDown(self) -> None:
        pass

    def test_get_tags_from_protocol(self) -> None:
        """Test case for get_tags_from_protocol

        Get all tags for an executed protocol
        """
        pass

    def test_get_tags_from_protocol_as_table(self) -> None:
        """Test case for get_tags_from_protocol_as_table

        Get all tags for an executed protocol in table format
        """
        pass


if __name__ == '__main__':
    unittest.main()
