# coding: utf-8

"""
    PPRL Protocol Manager Service API

    Protocol manager service for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_protocol_manager_service_api_client.models.germany_generator_config import GermanyGeneratorConfig

class TestGermanyGeneratorConfig(unittest.TestCase):
    """GermanyGeneratorConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GermanyGeneratorConfig:
        """Test GermanyGeneratorConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GermanyGeneratorConfig`
        """
        model = GermanyGeneratorConfig()
        if include_optional:
            return GermanyGeneratorConfig(
                seed = '',
                number_of_records = 56,
                include_household_structures = True,
                include_header = True,
                destination_folder = '',
                file_name = '',
                attributes = [
                    ''
                    ],
                source_name = ''
            )
        else:
            return GermanyGeneratorConfig(
        )
        """

    def testGermanyGeneratorConfig(self):
        """Test GermanyGeneratorConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
