# coding: utf-8

"""
    PPRL Protocol Manager Service API

    Protocol manager service for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_protocol_manager_service_api_client.api.actuator_api import ActuatorApi


class TestActuatorApi(unittest.TestCase):
    """ActuatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActuatorApi()

    def tearDown(self) -> None:
        pass

    def test_health(self) -> None:
        """Test case for health

        Actuator web endpoint 'health'
        """
        pass

    def test_info(self) -> None:
        """Test case for info

        Actuator web endpoint 'info'
        """
        pass

    def test_links(self) -> None:
        """Test case for links

        Actuator root web endpoint
        """
        pass

    def test_list_names(self) -> None:
        """Test case for list_names

        Actuator web endpoint 'metrics'
        """
        pass

    def test_mappings(self) -> None:
        """Test case for mappings

        Actuator web endpoint 'mappings'
        """
        pass

    def test_metric(self) -> None:
        """Test case for metric

        Actuator web endpoint 'metrics-requiredMetricName'
        """
        pass


if __name__ == '__main__':
    unittest.main()
