# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pprl_linkage_unit_service_api_client.models.batch_match_project_phase import BatchMatchProjectPhase
from typing import Optional, Set
from typing_extensions import Self

class BatchMatchProjectDto(BaseModel):
    """
    BatchMatchProjectDto
    """ # noqa: E501
    project_id: Optional[StrictStr] = Field(default=None, alias="projectId")
    last_update: Optional[StrictStr] = Field(default=None, alias="lastUpdate")
    method: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    dataset_id: Optional[StrictInt] = Field(default=None, alias="datasetId")
    interactive: Optional[StrictBool] = None
    configs: Optional[Dict[str, StrictStr]] = None
    current_state: Optional[StrictStr] = Field(default=None, alias="currentState")
    phases: Optional[Dict[str, BatchMatchProjectPhase]] = None
    __properties: ClassVar[List[str]] = ["projectId", "lastUpdate", "method", "description", "datasetId", "interactive", "configs", "currentState", "phases"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BatchMatchProjectDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in phases (dict)
        _field_dict = {}
        if self.phases:
            for _key_phases in self.phases:
                if self.phases[_key_phases]:
                    _field_dict[_key_phases] = self.phases[_key_phases].to_dict()
            _dict['phases'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BatchMatchProjectDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "projectId": obj.get("projectId"),
            "lastUpdate": obj.get("lastUpdate"),
            "method": obj.get("method"),
            "description": obj.get("description"),
            "datasetId": obj.get("datasetId"),
            "interactive": obj.get("interactive"),
            "configs": obj.get("configs"),
            "currentState": obj.get("currentState"),
            "phases": dict(
                (_k, BatchMatchProjectPhase.from_dict(_v))
                for _k, _v in obj["phases"].items()
            )
            if obj.get("phases") is not None
            else None
        })
        return _obj


