# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from pprl_linkage_unit_service_api_client.models.record_id_pair_dto import RecordIdPairDto
from typing import Optional, Set
from typing_extensions import Self

class GroundTruthDto(BaseModel):
    """
    Ground truth links of a dataset
    """ # noqa: E501
    dataset_id: Optional[StrictInt] = Field(default=None, alias="datasetId")
    record_id_pairs: Optional[List[RecordIdPairDto]] = Field(default=None, alias="recordIdPairs")
    __properties: ClassVar[List[str]] = ["datasetId", "recordIdPairs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroundTruthDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in record_id_pairs (list)
        _items = []
        if self.record_id_pairs:
            for _item_record_id_pairs in self.record_id_pairs:
                if _item_record_id_pairs:
                    _items.append(_item_record_id_pairs.to_dict())
            _dict['recordIdPairs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroundTruthDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datasetId": obj.get("datasetId"),
            "recordIdPairs": [RecordIdPairDto.from_dict(_item) for _item in obj["recordIdPairs"]] if obj.get("recordIdPairs") is not None else None
        })
        return _obj


