# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from pprl_linkage_unit_service_api_client.models.matcher_id_dto import MatcherIdDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MatchingCreationRequestDto(BaseModel):
    """
    Request for creating a matching definition.
    """ # noqa: E501
    weight_selection_method: Optional[StrictStr] = Field(default=None, alias="weightSelectionMethod")
    matching_creation_method: Optional[StrictStr] = Field(default=None, alias="matchingCreationMethod")
    base_matcher_id: Optional[MatcherIdDto] = Field(default=None, alias="baseMatcherId")
    output_matcher_id: Optional[MatcherIdDto] = Field(default=None, alias="outputMatcherId")
    attribute_weights: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, alias="attributeWeights")
    attribute_m_weights: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, alias="attributeMWeights")
    attribute_u_weights: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, alias="attributeUWeights")
    dataset_id: Optional[StrictInt] = Field(default=None, alias="datasetId")
    persist: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["weightSelectionMethod", "matchingCreationMethod", "baseMatcherId", "outputMatcherId", "attributeWeights", "attributeMWeights", "attributeUWeights", "datasetId", "persist"]

    @field_validator('weight_selection_method')
    def weight_selection_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'FELLEGI_SUNTER']):
            raise ValueError("must be one of enum values ('NONE', 'FELLEGI_SUNTER')")
        return value

    @field_validator('matching_creation_method')
    def matching_creation_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BASE_CONFIG_ADAPTION']):
            raise ValueError("must be one of enum values ('BASE_CONFIG_ADAPTION')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MatchingCreationRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base_matcher_id
        if self.base_matcher_id:
            _dict['baseMatcherId'] = self.base_matcher_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output_matcher_id
        if self.output_matcher_id:
            _dict['outputMatcherId'] = self.output_matcher_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MatchingCreationRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "weightSelectionMethod": obj.get("weightSelectionMethod"),
            "matchingCreationMethod": obj.get("matchingCreationMethod"),
            "baseMatcherId": MatcherIdDto.from_dict(obj["baseMatcherId"]) if obj.get("baseMatcherId") is not None else None,
            "outputMatcherId": MatcherIdDto.from_dict(obj["outputMatcherId"]) if obj.get("outputMatcherId") is not None else None,
            "attributeWeights": obj.get("attributeWeights"),
            "attributeMWeights": obj.get("attributeMWeights"),
            "attributeUWeights": obj.get("attributeUWeights"),
            "datasetId": obj.get("datasetId"),
            "persist": obj.get("persist")
        })
        return _obj


