# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from pprl_linkage_unit_service_api_client.models.record_id_dto import RecordIdDto
from typing import Optional, Set
from typing_extensions import Self

class RecordIdPairDto(BaseModel):
    """
    RecordIdPairDto
    """ # noqa: E501
    left_record_id: Optional[RecordIdDto] = Field(default=None, alias="leftRecordId")
    right_record_id: Optional[RecordIdDto] = Field(default=None, alias="rightRecordId")
    label: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["leftRecordId", "rightRecordId", "label"]

    @field_validator('label')
    def label_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['TRUE_MATCH', 'TRUE_NON_MATCH']):
            raise ValueError("must be one of enum values ('TRUE_MATCH', 'TRUE_NON_MATCH')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecordIdPairDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of left_record_id
        if self.left_record_id:
            _dict['leftRecordId'] = self.left_record_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of right_record_id
        if self.right_record_id:
            _dict['rightRecordId'] = self.right_record_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecordIdPairDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "leftRecordId": RecordIdDto.from_dict(obj["leftRecordId"]) if obj.get("leftRecordId") is not None else None,
            "rightRecordId": RecordIdDto.from_dict(obj["rightRecordId"]) if obj.get("rightRecordId") is not None else None,
            "label": obj.get("label")
        })
        return _obj


