# coding: utf-8

"""
    PPRL Linkage Unit Service API

    Linkage / Matching services for privacy-preserving record linkage

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from pprl_linkage_unit_service_api_client.models.record_dto import RecordDto
from pprl_linkage_unit_service_api_client.models.tag import Tag
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RecordPairWithRecordsDto(BaseModel):
    """
    RecordPairWithRecordsDto
    """ # noqa: E501
    record0: Optional[RecordDto] = None
    record1: Optional[RecordDto] = None
    project_id: Optional[StrictStr] = Field(default=None, alias="projectId")
    match_grade: Optional[StrictStr] = Field(default=None, alias="matchGrade")
    similarity: Optional[Union[StrictFloat, StrictInt]] = None
    properties: Optional[List[StrictStr]] = None
    attribute_similarities: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, alias="attributeSimilarities")
    tags: Optional[List[Tag]] = None
    __properties: ClassVar[List[str]] = ["record0", "record1", "projectId", "matchGrade", "similarity", "properties", "attributeSimilarities", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecordPairWithRecordsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of record0
        if self.record0:
            _dict['record0'] = self.record0.to_dict()
        # override the default output from pydantic by calling `to_dict()` of record1
        if self.record1:
            _dict['record1'] = self.record1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecordPairWithRecordsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "record0": RecordDto.from_dict(obj["record0"]) if obj.get("record0") is not None else None,
            "record1": RecordDto.from_dict(obj["record1"]) if obj.get("record1") is not None else None,
            "projectId": obj.get("projectId"),
            "matchGrade": obj.get("matchGrade"),
            "similarity": obj.get("similarity"),
            "properties": obj.get("properties"),
            "attributeSimilarities": obj.get("attributeSimilarities"),
            "tags": [Tag.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None
        })
        return _obj


