# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_generator_service_api_client.models.change_filter import ChangeFilter

class TestChangeFilter(unittest.TestCase):
    """ChangeFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeFilter:
        """Test ChangeFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangeFilter`
        """
        model = ChangeFilter()
        if include_optional:
            return ChangeFilter(
                min_changes = 56,
                max_changes = 56,
                changed_attributes = [
                    ''
                    ],
                unchanged_attributes = [
                    ''
                    ],
                require_all_listed_attributes = True
            )
        else:
            return ChangeFilter(
        )
        """

    def testChangeFilter(self):
        """Test ChangeFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
