# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_generator_service_api_client.models.generic_raw_record import GenericRawRecord

class TestGenericRawRecord(unittest.TestCase):
    """GenericRawRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenericRawRecord:
        """Test GenericRawRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenericRawRecord`
        """
        model = GenericRawRecord()
        if include_optional:
            return GenericRawRecord(
                voter_id = '',
                snap_shot = pprl_data_generator_service_api_client.models.date_info.DateInfo(
                    date = '', 
                    year = 56, 
                    month = 56, 
                    day = 56, 
                    as_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                attributes = {
                    'key' : ''
                    }
            )
        else:
            return GenericRawRecord(
        )
        """

    def testGenericRawRecord(self):
        """Test GenericRawRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
