# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_generator_service_api_client.api.data_selector_api import DataSelectorApi


class TestDataSelectorApi(unittest.TestCase):
    """DataSelectorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataSelectorApi()

    def tearDown(self) -> None:
        pass

    def test_create_cluster_order(self) -> None:
        """Test case for create_cluster_order

        """
        pass

    def test_delete_cluster_order(self) -> None:
        """Test case for delete_cluster_order

        """
        pass

    def test_example_usvr_selection_config(self) -> None:
        """Test case for example_usvr_selection_config

        """
        pass

    def test_prepare_import_panse_ncvr(self) -> None:
        """Test case for prepare_import_panse_ncvr

        Import NCVR data
        """
        pass

    def test_retrieve_clusters(self) -> None:
        """Test case for retrieve_clusters

        """
        pass

    def test_select(self) -> None:
        """Test case for select

        """
        pass


if __name__ == '__main__':
    unittest.main()
