# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_generator_service_api_client.models.record_cluster import RecordCluster

class TestRecordCluster(unittest.TestCase):
    """RecordCluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordCluster:
        """Test RecordCluster
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordCluster`
        """
        model = RecordCluster()
        if include_optional:
            return RecordCluster(
                id = pprl_data_generator_service_api_client.models.object_id.ObjectId(
                    timestamp = 56, 
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                domain_id = '',
                origin = pprl_data_generator_service_api_client.models.generic_raw_record_with_dates.GenericRawRecordWithDates(
                    record = pprl_data_generator_service_api_client.models.generic_raw_record.GenericRawRecord(
                        voter_id = '', 
                        snap_shot = pprl_data_generator_service_api_client.models.date_info.DateInfo(
                            date = '', 
                            year = 56, 
                            month = 56, 
                            day = 56, 
                            as_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                        attributes = {
                            'key' : ''
                            }, ), 
                    occurs_in = [
                        pprl_data_generator_service_api_client.models.date_info.DateInfo(
                            date = '', 
                            year = 56, 
                            month = 56, 
                            day = 56, 
                            as_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                        ], ),
                duplicates = [
                    pprl_data_generator_service_api_client.models.duplicate.Duplicate(
                        record = pprl_data_generator_service_api_client.models.generic_raw_record.GenericRawRecord(
                            voter_id = '', 
                            snap_shot = pprl_data_generator_service_api_client.models.date_info.DateInfo(
                                date = '', 
                                year = 56, 
                                month = 56, 
                                day = 56, 
                                as_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                            attributes = {
                                'key' : ''
                                }, ), 
                        occurs_in = [
                            pprl_data_generator_service_api_client.models.date_info.DateInfo(
                                date = '', 
                                year = 56, 
                                month = 56, 
                                day = 56, 
                                as_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                            ], 
                        changes = {
                            'key' : True
                            }, 
                        timespan_in_days = [
                            56
                            ], )
                    ]
            )
        else:
            return RecordCluster(
        )
        """

    def testRecordCluster(self):
        """Test RecordCluster"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
