# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pprl_data_generator_service_api_client.api.data_generator_api import DataGeneratorApi


class TestDataGeneratorApi(unittest.TestCase):
    """DataGeneratorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataGeneratorApi()

    def tearDown(self) -> None:
        pass

    def test_example_germany_generator_configuration(self) -> None:
        """Test case for example_germany_generator_configuration

        Get example configuration
        """
        pass

    def test_generate(self) -> None:
        """Test case for generate

        Generate synthetic records
        """
        pass


if __name__ == '__main__':
    unittest.main()
